services:
  php:
    build: .
    container_name: camagru_php
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./public:/var/www/html
      - ./config/msmtprc:/etc/msmtprc
    command: php -S 0.0.0.0:8080 -t /app/public
